/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppAppImage from './AppAppImage';

/**
 * The App model module.
 * @module model/App
 * @version 1.0.0
 */
class App {
    /**
     * Constructs a new <code>App</code>.
     * @alias module:model/App
     * @param appTitle {String} 
     * @param appDescription {String} 
     * @param appImage {module:model/AppAppImage} 
     */
    constructor(appTitle, appDescription, appImage) { 
        
        App.initialize(this, appTitle, appDescription, appImage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, appTitle, appDescription, appImage) { 
        obj['appTitle'] = appTitle;
        obj['appDescription'] = appDescription;
        obj['appImage'] = appImage;
    }

    /**
     * Constructs a <code>App</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/App} obj Optional instance to populate.
     * @return {module:model/App} The populated <code>App</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new App();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('appTitle')) {
                obj['appTitle'] = ApiClient.convertToType(data['appTitle'], 'String');
            }
            if (data.hasOwnProperty('appDescription')) {
                obj['appDescription'] = ApiClient.convertToType(data['appDescription'], 'String');
            }
            if (data.hasOwnProperty('appImage')) {
                obj['appImage'] = AppAppImage.constructFromObject(data['appImage']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
App.prototype['_id'] = undefined;

/**
 * @member {String} appTitle
 */
App.prototype['appTitle'] = undefined;

/**
 * @member {String} appDescription
 */
App.prototype['appDescription'] = undefined;

/**
 * @member {module:model/AppAppImage} appImage
 */
App.prototype['appImage'] = undefined;






export default App;

